{% set name = "levmar" %}
{% set version = "2.6" %}
{% set build_number = 8 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://src.fedoraproject.org/repo/pkgs/rpms/levmar/levmar-2.6.tgz/sha512/5b4c64b63be9b29d6ad2df435af86cd2c2e3216313378561a670ac6a392a51bbf1951e96c6b1afb77c570f23dd8e194017808e46929fec2d8d9a7fe6cf37022b/levmar-2.6.tgz
    sha512: 5b4c64b63be9b29d6ad2df435af86cd2c2e3216313378561a670ac6a392a51bbf1951e96c6b1afb77c570f23dd8e194017808e46929fec2d8d9a7fe6cf37022b
    patches:
        - levmar-cmake-shared.patch

build:
    number: {{ build_number }}
    run_exports:
        - {{ pin_subpackage('levmar', max_pin='x.x') }}

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('c') }}
    host:
        - libcblas>=3.8.0
        - liblapack>=3.8.0
    run:
        - {{ pin_compatible('libcblas', min_pin='x.x', max_pin='x') }}
        - {{ pin_compatible('liblapack', min_pin='x.x', max_pin='x') }}

test:
    commands:
        - lmdemo

about:
    home: http://users.ics.forth.gr/~lourakis/levmar/ 
    license: GPL2
    license_file: LICENSE
    summary: Levenberg-Marquardt nonlinear least squares algorithm

